# Generated by Django 5.2.10 on 2026-01-30 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_cancel_note_orderitem_cancel_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cancel_note',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cancel_reason',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cancelled_at',
        ),
    ]
